apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb
  labels:
    app: simpleweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
      - name: simpleweb
        image: lispavel/simpleweb
        ports:
        - containerPort: 80
        env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: message-configmap
                key: message
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          failureThreshold: 1
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /health
            port: 80
          failureThreshold: 12
          periodSeconds: 5